version: '3.8'
services:
  frontend-react:
    build: ./AST-checker/frontend
    ports:
      - "2355:2355"
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:2354
    deploy:
      replicas: 2
    depends_on:
      - backend-nodejs

  backend-nodejs:
    build: ./AST-checker/backend
    ports:
      - "2354:2354"
    environment:
      NODE_ENV: development
      DATABASE_URL: mongodb://mongo:27017/mydatabase
      SERVER_PORT: 2354
      MONGO_URI: mongodb://mongo:27017/ast_rule_engine  # Use mongo service name instead of localhost
    deploy:
      replicas: 2
    depends_on:
      - mongo

  frontend-nextjs:
    build: ./Weather-app/app
    ports:
      - "2353:2353"
    environment:
      NODE_ENV: development
      WEATHER_API_KEY: YOUR_WEATHER_API_KEY_HERE
    deploy:
      replicas: 2

  mongo:
    image: mongo:latest
    ports:
      - "2356:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
