version: "3.8"
services:
  frontend-react:
    build: ./AST-checker/frontend
    ports:
      - "3004:3000"
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:3005
    deploy:
      replicas: 1
    depends_on:
      - backend-nodejs

  backend-nodejs:
    build: ./AST-checker/backend
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: development
      DATABASE_URL: mongodb://root:example@mongo:27017/mydatabase?authSource=admin
      SERVER_PORT: 3005
      MONGO_URI: mongodb://root:example@mongo:27017/ast_rule_engine?authSource=admin
    deploy:
      replicas: 1
    depends_on:
      - mongo

  frontend-nextjs:
    build: ./Weather-app/app
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: development
      WEATHER_API_KEY: YOUR_WEATHER_API_KEY_HERE
    deploy:
      replicas: 1

  mongo:
    image: mongo:latest
    ports:
      - "2356:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
